### ISSUE TITLE
grcov v0.5.14 broke the --output-file option

### ISSUE THREAD

**Issue by rye** [actions-rs/grcov#70]
After v0.5.14 of grcov was released, `actions-rs/grcov` invocations stopped working because the `--output-file` command-line option is no longer recognized by the grcov binary.

Looking at [the compare](https://github.com/mozilla/grcov/compare/v0.5.13...v0.5.14), (upstream does not keep a proper changelog) it appears that https://github.com/mozilla/grcov/commit/26acaa0c65c34278d0df5083b46468c22ba13f8b is the culprit, and does not include a backwards compatibility mechanism.  It appears that a simple change from `output-file` to `output-path` is all that is necessary to resolve this, and I'm preparing a patch for that.  This issue is mostly just for tracking.

**Comment by svartalf** [comment]
Thank you for the patch, published in `v0.1.6` tag and available via the `actions-rs/grcov@v0.1` tag!
